-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jun 25, 2024 at 02:07 AM
-- Server version: 8.2.0
-- PHP Version: 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `php_project`
--

-- --------------------------------------------------------

--
-- Table structure for table `admins`
--

DROP TABLE IF EXISTS `admins`;
CREATE TABLE IF NOT EXISTS `admins` (
  `admin_id` int NOT NULL AUTO_INCREMENT,
  `admin_name` varchar(250) NOT NULL,
  `admin_email` text NOT NULL,
  `admin_password` text NOT NULL,
  PRIMARY KEY (`admin_id`)
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `admins`
--

INSERT INTO `admins` (`admin_id`, `admin_name`, `admin_email`, `admin_password`) VALUES
(2, 'Admin', 'admin@gmail.com', '$2y$10$Xxejv3QqXCwTEKRuhWUo2uNHGbUr1.Or0R/q750W63agJw430JgDq');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

DROP TABLE IF EXISTS `orders`;
CREATE TABLE IF NOT EXISTS `orders` (
  `order_id` int NOT NULL AUTO_INCREMENT,
  `order_cost` decimal(10,2) NOT NULL,
  `order_status` varchar(50) NOT NULL,
  `user_id` int DEFAULT NULL,
  `user_phone` varchar(15) DEFAULT NULL,
  `user_city` varchar(100) DEFAULT NULL,
  `user_address` varchar(255) DEFAULT NULL,
  `order_date` date NOT NULL,
  PRIMARY KEY (`order_id`),
  KEY `user_id` (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `order_items`
--

DROP TABLE IF EXISTS `order_items`;
CREATE TABLE IF NOT EXISTS `order_items` (
  `item_id` int NOT NULL AUTO_INCREMENT,
  `order_id` int DEFAULT NULL,
  `product_id` int DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `product_image` varchar(255) DEFAULT NULL,
  `product_price` decimal(6,2) DEFAULT NULL,
  `product_quantity` int DEFAULT NULL,
  `user_id` int DEFAULT NULL,
  `order_date` date DEFAULT NULL,
  PRIMARY KEY (`item_id`),
  KEY `order_id` (`order_id`),
  KEY `product_id` (`product_id`),
  KEY `product_image` (`product_image`(250)),
  KEY `user_id` (`user_id`),
  KEY `order_date` (`order_date`),
  KEY `product_price` (`product_price`),
  KEY `product_quantity` (`product_quantity`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `product_id` int NOT NULL AUTO_INCREMENT,
  `product_name` varchar(100) NOT NULL,
  `product_author` varchar(100) NOT NULL,
  `product_category` varchar(100) NOT NULL,
  `product_description` varchar(6000) NOT NULL,
  `product_image` varchar(255) NOT NULL,
  `product_price` decimal(10,2) NOT NULL,
  `product_special_offer` decimal(10,2) NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=InnoDB AUTO_INCREMENT=43 DEFAULT CHARSET=utf16;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_name`, `product_author`, `product_category`, `product_description`, `product_image`, `product_price`, `product_special_offer`) VALUES
(1, 'Dune', 'Frank Herbert', 'Thriller', 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world where the only thing of value is the “spice” melange, a drug capable of extending life and enhancing consciousness. Coveted across the known universe, melange is a prize worth killing for...  When House Atreides is betrayed, the destruction of Paul’s family will set the boy on a journey toward a destiny greater than he could ever have imagined. And as he evolves into the mysterious man known as Muad’Dib, he will bring to fruition humankind’s most ancient and unattainable dream.', 'dune.jpg', 4855.91, 4620.20),
(2, 'The Serial Killer', 'Oyinkan Braithwaite', 'Thriller', 'When Korede\'s dinner is interrupted one night by a distress call from her sister, Ayoola, she knows what\'s expected of her: bleach, rubber gloves, nerves of steel and a strong stomach. This\'ll be the third boyfriend Ayoola\'s dispatched in, quote, self-defence and the third mess that her lethal little sibling has left Korede to clear away. She should probably go to the police for the good of the menfolk of Nigeria, but she loves her sister and, as they say, family always comes first. Until, that is, Ayoola starts dating the doctor where Korede works as a nurse. Korede\'s long been in love with him, and isn\'t prepared to see him wind up with a knife in his back: but to save one would mean sacrificing the other...My Sister, the Serial Killer is a blackly comic novel about how blood is thicker - and more difficult to get out of the carpet - than water...', 'mysister,theserialkiller.jpg', 3600.00, 3500.20),
(4, 'Homecoming', 'Kate Morton', 'Fantasy', 'In this clever and swoonworthy YA debut from the New York Times bestselling author of The Love Hypothesis, life\'s moving pieces bring rival chess players together in a match for the heart.\r\n\r\nMallory Greenleaf is done with chess. Every move counts nowadays; after the sport led to the destruction of her family four years earlier, Mallory\'s focus is on her mom, her sisters, and the dead-end job that keeps the lights on. That is, until she begrudgingly agrees to play in one last charity tournament and inadvertently wipes the board with notorious \"Kingkiller\" Nolan Sawyer: current world champion and reigning Bad Boy of chess.\r\n\r\nNolan\'s loss to an unknown rook-ie shocks everyone. What\'s even more confusing? His desire to cross pawns again. What kind of gambit is Nolan playing? The smart move would be to walk away. Resign. Game over. But Mallory\'s victory opens the door to sorely needed cash-prizes and despite everything, she can\'t help feeling drawn to the enigmatic strategist....\r\n\r\nAs she rockets up the ranks, Mallory struggles to keep her family safely separated from the game that wrecked it in the first place. And as her love for the sport she so desperately wanted to hate begins to rekindle, Mallory quickly realizes that the games aren\'t only on the board, the spotlight is brighter than she imagined, and the competition can be fierce (-ly attractive. And intelligent...and infuriating...)', 'homecoming.jpg', 2699.91, 2400.00),
(5, 'The Water Dancer', 'Ta-Nehisi Coates', 'Thriller', 'In this clever and swoonworthy YA debut from the New York Times bestselling author of The Love Hypothesis, life\'s moving pieces bring rival chess players together in a match for the heart.\r\n\r\nMallory Greenleaf is done with chess. Every move counts nowadays; after the sport led to the destruction of her family four years earlier, Mallory\'s focus is on her mom, her sisters, and the dead-end job that keeps the lights on. That is, until she begrudgingly agrees to play in one last charity tournament and inadvertently wipes the board with notorious \"Kingkiller\" Nolan Sawyer: current world champion and reigning Bad Boy of chess.\r\n\r\nNolan\'s loss to an unknown rook-ie shocks everyone. What\'s even more confusing? His desire to cross pawns again. What kind of gambit is Nolan playing? The smart move would be to walk away. Resign. Game over. But Mallory\'s victory opens the door to sorely needed cash-prizes and despite everything, she can\'t help feeling drawn to the enigmatic strategist....\r\n\r\nAs she rockets up the ranks, Mallory struggles to keep her family safely separated from the game that wrecked it in the first place. And as her love for the sport she so desperately wanted to hate begins to rekindle, Mallory quickly realizes that the games aren\'t only on the board, the spotlight is brighter than she imagined, and the competition can be fierce (-ly attractive. And intelligent...and infuriating...)\r\n', 'thewaterdancer.jpg', 2899.91, 2500.60),
(6, 'The Hired Girl', 'Laura Amy Schlitz', 'Romance', 'Today Miss Chandler gave me this beautiful book. I vow that I will never forget her kindness to me, and I will use this book as she told me to—that I will write in it with truth and refinement…But who could be refined living at Steeple Farm?\r\n\r\nFourteen-year-old Joan Skraggs, just like the heroines in her beloved novels, yearns for real life and true love. But what hope is there for adventure, beauty, or art on a hardscrabble farm in Pennsylvania where the work never ends? Over the summer of 1911, Joan pours her heart out into her diary as she seeks a new, better life for herself—because maybe, just maybe, a hired girl cleaning and cooking for six dollars a week can become what a farm girl could only dream of—a woman with a future.\r\n\r\nInspired by her grandmother’s journal, Newbery Medalist Laura Amy Schlitz brings her sharp wit and keen eye to early twentieth-century America in a comedic tour de force destined to become a modern classic. Joan’s journey from the muck of the chicken coop to the comforts of a society household in Baltimore (Electricity! Carpet sweepers! Sending out the laundry!) takes its reader on an exploration of feminism and housework, religion and literature, love and loyalty, cats, hats, bunions, and burns.', 'thehiredgirl.jpg', 2934.11, 2740.30),
(7, 'Yellowface', 'R. F. Kuang', 'Crime Fiction', 'Athena Liu is a literary darling and June Hayward is literally nobody.\r\n\r\nWhite lies\r\nWhen Athena dies in a freak accident, June steals her unpublished manuscript and publishes it as her own under the ambiguous name Juniper Song.\r\n\r\nDark humour\r\nBut as evidence threatens June’s stolen success, she will discover exactly how far she will go to keep what she thinks she deserves.\r\n\r\nDeadly consequences…\r\nWhat happens next is entirely everyone else’s fault.\r\n\r\nWith its totally immersive first-person voice, Yellowface grapples with questions of diversity, racism, and cultural appropriation, as well as the terrifying alienation of social media. R.F. Kuang’s novel is timely, razor-sharp, and eminently readable.', 'yellowface.jpg', 4497.79, 0.00),
(8, 'Weyward', 'Emilia Hart', 'Fantasy', 'I am a Weyward, and wild inside.\r\n\r\n2019: Under cover of darkness, Kate flees London for ramshackle Weyward Cottage, inherited from a great aunt she barely remembers. With its tumbling ivy and overgrown garden, the cottage is worlds away from the abusive partner who tormented Kate. But she begins to suspect that her great aunt had a secret. One that lurks in the bones of the cottage, hidden ever since the witch-hunts of the 17th century.\r\n\r\n1619: Altha is awaiting trial for the murder of a local farmer who was stampeded to death by his herd. As a girl, Altha’s mother taught her their magic, a kind not rooted in spell casting but in a deep knowledge of the natural world. But unusual women have always been deemed dangerous, and as the evidence for witchcraft is set out against Altha, she knows it will take all of her powers to maintain her freedom.\r\n\r\n1942: As World War II rages, Violet is trapped in her family\'s grand, crumbling estate. Straitjacketed by societal convention, she longs for the robust education her brother receives––and for her mother, long deceased, who was rumored to have gone mad before her death. The only traces Violet has of her are a locket bearing the initial W and the word weyward scratched into the baseboard of her bedroom.\r\n\r\nWeaving together the stories of three extraordinary women across five centuries, Emilia Hart\'s Weyward is an enthralling novel of female resilience and the transformative power of the natural world.', 'weyward.jpg', 3597.63, 0.00),
(9, 'Housemaid\'s Secret', 'Freida McFadden', 'Thriller', 'As he continues showing me their incredible penthouse apartment, I have a terrible feeling about the woman behind closed doors. But I can\'t risk losing this job – not if I want to keep my darkest secret safe . . .\r\n\r\nIt\'s hard to find an employer who doesn\'t ask too many questions about my past. So I thank my lucky stars that the Garricks miraculously give me a job, cleaning their stunning penthouse with views across the city and preparing fancy meals in their shiny kitchen. I can work here for a while, stay quiet until I get what I want. It\'s almost perfect. But I still haven\'t met Mrs Garrick, or seen inside the guest bedroom. I\'m sure I hear her crying. I notice spots of blood around the neck of her white nightgowns when I\'m doing laundry. And one day I can\'t help but knock on the door. When it gently swings open, what I see inside changes everything...\r\n\r\nThat\'s when I make a promise. After all, I\'ve done this before. I can protect Mrs. Garrick while keeping my own secrets locked up safe. Douglas Garrick has done wrong. He is going to pay. It\'s simply a question of how far I\'m willing to go...', 'housemaidssecret.jpg', 4500.79, 0.00),
(10, 'Happy Place', 'Emily Henry', 'Romance', 'Harriet and Wyn have been the perfect couple since they met in college—they go together like salt and pepper, honey and tea, lobster and rolls. Except, now—for reasons they’re still not discussing—they don’t.\r\n\r\nThey broke up six months ago. And still haven’t told their best friends.\r\n\r\nWhich is how they find themselves sharing the largest bedroom at the Maine cottage that has been their friend group’s yearly getaway for the last decade. Their annual respite from the world, where for one vibrant, blue week they leave behind their daily lives; have copious amounts of cheese, wine, and seafood; and soak up the salty coastal air with the people who understand them most.\r\n\r\nOnly this year, Harriet and Wyn are lying through their teeth while trying not to notice how desperately they still want each other. Because the cottage is for sale and this is the last week they’ll all have together in this place. They can’t stand to break their friends’ hearts, and so they’ll play their parts. Harriet will be the driven surgical resident who never starts a fight, and Wyn will be the laid-back charmer who never lets the cracks show. It’s a flawless plan (if you look at it from a great distance and through a pair of sunscreen-smeared sunglasses). After years of being in love, how hard can it be to fake it for one week… in front of those who know you best?\r\n\r\nA couple who broke up months ago make a pact to pretend to still be together for their annual weeklong vacation with their best friends in this glittering and wise new novel from #1 New York Times bestselling author Emily Henry.', 'happyplace.jpg', 3597.63, 0.00),
(11, 'Fourth Wing', 'Rebecca Yarros', 'Mystery', 'Enter the brutal and elite world of a war college for dragon riders from USA Today bestselling author Rebecca Yarros.\r\n\r\nTwenty-year-old Violet Sorrengail was supposed to enter the Scribe Quadrant, living a quiet life among books and history. Now, the commanding general—also known as her tough-as-talons mother—has ordered Violet to join the hundreds of candidates striving to become the elite of Navarre: dragon riders.\r\n\r\nBut when you’re smaller than everyone else and your body is brittle, death is only a heartbeat away...because dragons don’t bond to “fragile” humans. They incinerate them.\r\n\r\nWith fewer dragons willing to bond than cadets, most would kill Violet to better their own chances of success. The rest would kill her just for being her mother’s daughter—like Xaden Riorson, the most powerful and ruthless wingleader in the Riders Quadrant.\r\n\r\nShe’ll need every edge her wits can give her just to see the next sunrise.\r\n\r\nYet, with every day that passes, the war outside grows more deadly, the kingdom\'s protective wards are failing, and the death toll continues to rise. Even worse, Violet begins to suspect leadership is hiding a terrible secret.\r\n\r\nFriends, enemies, lovers. Everyone at Basgiath War College has an agenda—because once you enter, there are only two ways out: graduate or die', 'fourthwing.jpg', 5565.98, 0.00),
(12, 'Hell Bent', 'Leight Barbugo', 'Thriller', 'Wealth. Power. Murder. Magic. Alex Stern is back and the Ivy League is going straight to hell in #1 New York Times bestselling author Leigh Bardugo\'s Hell Bent.\r\n\r\nFind a gateway to the underworld. Steal a soul out of hell. A simple plan, except people who make this particular journey rarely come back. But Galaxy “Alex” Stern is determined to break Darlington out of purgatory―even if it costs her a future at Lethe and at Yale.\r\n\r\nForbidden from attempting a rescue, Alex and Dawes can’t call on the Ninth House for help, so they assemble a team of dubious allies to save the gentleman of Lethe. Together, they will have to navigate a maze of arcane texts and bizarre artifacts to uncover the societies’ most closely guarded secrets, and break every rule doing it. But when faculty members begin to die off, Alex knows these aren’t just accidents. Something deadly is at work in New Haven, and if she is going to survive, she’ll have to reckon with the monsters of her past and a darkness built into the university’s very walls.\r\n\r\nThick with history and packed with Bardugo’s signature twists, Hell Bent brings to life an intricate world full of magic, violence, and all too real monsters.', 'hellbent.jpg', 5703.15, 0.00),
(13, 'Lives of Puppets', 'T. J Klune', 'Fantasy', 'In a strange little home built into the branches of a grove of trees, live three robots—fatherly inventor android Giovanni Lawson, a pleasantly sadistic nurse machine, and a small vacuum desperate for love and attention. Victor Lawson, a human, lives there too. They’re a family, hidden and safe.\r\n\r\nThe day Vic salvages and repairs an unfamiliar android labelled “HAP,” he learns of a shared dark past between Hap and Gio–a past spent hunting humans.\r\n\r\nWhen Hap unwittingly alerts robots from Gio’s former life to their whereabouts, the family is no longer hidden and safe. Gio is captured and taken back to his old laboratory in the City of Electric Dreams. So together, the rest of Vic’s assembled family must journey across an unforgiving and otherworldly country to rescue Gio from decommission, or worse, reprogramming.\r\n\r\nAlong the way to save Gio, amid conflicted feelings of betrayal and affection for Hap, Vic must decide for himself: Can he accept love with strings attached?\r\n\r\nInspired by Carlo Collodi\'s The Adventures of Pinocchio, and like Swiss Family Robinson meets Wall-E, In the Lives of Puppets is a masterful stand-alone fantasy adventure from the beloved author who brought you The House in the Cerulean Sea and Under the Whispering Door.', 'inthelivesofpuppets.jpg', 3799.10, 0.00),
(14, 'Holly', 'Stephen King', 'Crime Fiction', 'Holly Gibney, one of Stephen King’s most compelling and ingeniously resourceful characters, returns in this thrilling novel to solve the gruesome truth behind multiple disappearances in a midwestern town.\r\n\r\n“Sometimes the universe throws you a rope.” — BILL HODGES\r\n\r\nStephen King’s Holly marks the triumphant return of beloved King character Holly Gibney. Readers have witnessed Holly’s gradual transformation from a shy (but also brave and ethical) recluse in Mr. Mercedes to Bill Hodges’s partner in Finders Keepers to a full-fledged, smart, and occasionally tough private detective in The Outsider. In King’s new novel, Holly is on her own, and up against a pair of unimaginably depraved and brilliantly disguised adversaries.\r\n\r\nWhen Penny Dahl calls the Finders Keepers detective agency hoping for help locating her missing daughter, Holly is reluctant to accept the case. Her partner, Pete, has Covid. Her (very complicated) mother has just died. And Holly is meant to be on leave. But something in Penny Dahl’s desperate voice makes it impossible for Holly to turn her down.\r\n\r\nMere blocks from where Bonnie Dahl disappeared live Professors Rodney and Emily Harris. They are the picture of bourgeois respectability: married octogenarians, devoted to each other, and semi-retired lifelong academics. But they are harboring an unholy secret in the basement of their well-kept, book-lined home, one that may be related to Bonnie’s disappearance. And it will prove nearly impossible to discover what they are up to: they are savvy, they are patient, and they are ruthless.\r\n\r\nHolly must summon all her formidable talents to outthink and outmaneuver the shockingly twisted professors in this chilling new masterwork from Stephen King.', 'holly.jpg', 4501.86, 0.00),
(15, 'Divine Rivals', 'Rebecca Ross', 'Romance', 'When two young rival journalists find love through a magical connection, they must face the depths of hell, in a war among gods, to seal their fate forever.\r\n\r\nAfter centuries of sleep, the gods are warring again. But eighteen-year-old Iris Winnow just wants to hold her family together. Her mother is suffering from addiction and her brother is missing from the front lines. Her best bet is to win the columnist promotion at the Oath Gazette.\r\n\r\nTo combat her worries, Iris writes letters to her brother and slips them beneath her wardrobe door, where they vanish—into the hands of Roman Kitt, her cold and handsome rival at the paper. When he anonymously writes Iris back, the two of them forge a connection that will follow Iris all the way to the front lines of battle: for her brother, the fate of mankind, and love.\r\n\r\nShadow and Bone meets Lore in Rebecca Ross\'s Divine Rivals, an epic enemies-to-lovers fantasy novel filled with hope and heartbreak, and the unparalleled power of love.', 'divinerivals.jpg', 5286.63, 0.00),
(16, 'Check & Mate', 'Ali Hazelwood', 'Romance', 'In this clever and swoonworthy YA debut from the New York Times bestselling author of The Love Hypothesis, life\'s moving pieces bring rival chess players together in a match for the heart.\r\n\r\nMallory Greenleaf is done with chess. Every move counts nowadays; after the sport led to the destruction of her family four years earlier, Mallory\'s focus is on her mom, her sisters, and the dead-end job that keeps the lights on. That is, until she begrudgingly agrees to play in one last charity tournament and inadvertently wipes the board with notorious \"Kingkiller\" Nolan Sawyer: current world champion and reigning Bad Boy of chess.\r\n\r\nNolan\'s loss to an unknown rook-ie shocks everyone. What\'s even more confusing? His desire to cross pawns again. What kind of gambit is Nolan playing? The smart move would be to walk away. Resign. Game over. But Mallory\'s victory opens the door to sorely needed cash-prizes and despite everything, she can\'t help feeling drawn to the enigmatic strategist....\r\n\r\nAs she rockets up the ranks, Mallory struggles to keep her family safely separated from the game that wrecked it in the first place. And as her love for the sport she so desperately wanted to hate begins to rekindle, Mallory quickly realizes that the games aren\'t only on the board, the spotlight is brighter than she imagined, and the competition can be fierce (-ly attractive. And intelligent...and infuriating...)', 'check&mate.jpg', 2699.91, 0.00),
(17, 'Poverty, by America', 'Matthew Desmond', 'Thriller', 'The Pulitzer Prize–winning, bestselling author of Evicted reimagines the debate on poverty, making a new and bracing argument about why it persists in America: because the rest of us benefit from it.\r\n\r\nONE OF THE MOST ANTICIPATED BOOKS OF 2023: The Washington Post, Time, Esquire, Newsweek, Minneapolis Star Tribune, Elle, Salon, Lit Hub, Kirkus Reviews\r\n\r\nThe United States, the richest country on earth, has more poverty than any other advanced democracy. Why? Why does this land of plenty allow one in every eight of its children to go without basic necessities, permit scores of its citizens to live and die on the streets, and authorize its corporations to pay poverty wages?\r\n\r\nIn this landmark book, acclaimed sociologist Matthew Desmond draws on history, research, and original reporting to show how affluent Americans knowingly and unknowingly keep poor people poor. Those of us who are financially secure exploit the poor, driving down their wages while forcing them to overpay for housing and access to cash and credit. We prioritize the subsidization of our wealth over the alleviation of poverty, designing a welfare state that gives the most to those who need the least. And we stockpile opportunity in exclusive communities, creating zones of concentrated riches alongside those of concentrated despair. Some lives are made small so that others may grow.\r\n\r\nElegantly written and fiercely argued, this compassionate book gives us new ways of thinking about a morally urgent problem. It also helps us imagine solutions. Desmond builds a startlingly original and ambitious case for ending poverty. He calls on us all to become poverty abolitionists, engaged in a politics of collective belonging to usher in a new age of shared prosperity and, at last, true freedom.', 'povertybuyamerica.jpg', 4201.53, 0.00),
(19, 'Get It Together', 'Jesse Watters', 'Fiction', 'AN INSTANT #1 NEW YORK TIMES BESTSELLER\r\n\r\nCan the political be way too personal? What if most radical activists are trying to change their lives by changing the whole country?\r\n\r\nWhen Jesse Watters set out to interview a few dozen radical activists to find out where their wild ideas came from, he discovered two things that shocked him:\r\n\r\nFirst, he liked these people.\r\n\r\nSecond, their political positions were not primarily from books, teachers, or other activists. They originated in personal drama. Most of these people didn’t need legislation. They needed a therapist.\r\n\r\nIn Get It Together, the number one New York Times bestselling author and Fox News primetime host takes on Wokeism in a way no one else has. Through a series of (sometimes very) personal interviews with some of the most radical activists in the country, Watters discovers that these activists may be overlooking the most important change they need to make—within themselves.\r\n\r\nFrom activists working for climate change salvation, Black supremacy, and social justice to a professional cuddler and a transwoman who identifies as a wolf, Watters shows how many well-intentioned Americans have bought into causes invented and run by people who are illogical, emotional, and ill-informed.\r\n\r\nThrough their stories, Watters uncovers common threads—childhood traumas, broken relationships, and a lack of introspection. What if the people obsessed with the end of the world are just hurting from how this one has treated them? What if that, rather than ideological disagreements, is the deeper root of our country’s political divide?\r\n\r\nFunny, fresh, and fascinating, Get It Together is sure to spark important conversations, and to inspire us to see one another not as political opponents, but as real and broken human beings.', 'getittogether.jpg', 5646.09, 0.00),
(20, 'Glad My Mom Died', 'Jennette McCurdy', 'Thriller', 'A heartbreaking and hilarious memoir by iCarly and Sam & Cat star Jennette McCurdy about her struggles as a former child actor—including eating disorders, addiction, and a complicated relationship with her overbearing mother—and how she retook control of her life.\r\n\r\nJennette McCurdy was six years old when she had her first acting audition. Her mother’s dream was for her only daughter to become a star, and Jennette would do anything to make her mother happy. So she went along with what Mom called “calorie restriction,” eating little and weighing herself five times a day. She endured extensive at-home makeovers while Mom chided, “Your eyelashes are invisible, okay? You think Dakota Fanning doesn’t tint hers?” She was even showered by Mom until age sixteen while sharing her diaries, email, and all her income.\r\n\r\nIn I’m Glad My Mom Died, Jennette recounts all this in unflinching detail—just as she chronicles what happens when the dream finally comes true. Cast in a new Nickelodeon series called iCarly , she is thrust into fame. Though Mom is ecstatic, emailing fan club moderators and getting on a first-name basis with the paparazzi (“Hi Gale!”), Jennette is riddled with anxiety, shame, and self-loathing, which manifest into eating disorders, addiction, and a series of unhealthy relationships. These issues only get worse when, soon after taking the lead in the iCarly spinoff Sam & Cat alongside Ariana Grande, her mother dies of cancer. Finally, after discovering therapy and quitting acting, Jennette embarks on recovery and decides for the first time in her life what she really wants.\r\n\r\nTold with refreshing candor and dark humor, I’m Glad My Mom Died is an inspiring story of resilience, independence, and the joy of shampooing your own hair.', 'gladmymomdied.jpg', 3597.63, 0.00),
(21, 'The Wager', 'David Grann', 'Fantasy', 'From the #1 New York Times bestselling author of Killers of the Flower Moon, a page-turning story of shipwreck, survival, and savagery, culminating in a court martial that reveals a shocking truth. The powerful narrative reveals the deeper meaning of the events on the Wager, showing that it was not only the captain and crew who ended up on trial, but the very idea of empire.\r\n\r\nOn January 28, 1742, a ramshackle vessel of patched-together wood and cloth washed up on the coast of Brazil. Inside were thirty emaciated men, barely alive, and they had an extraordinary tale to tell. They were survivors of His Majesty\'s Ship the Wager, a British vessel that had left England in 1740 on a secret mission during an imperial war with Spain. While the Wager had been chasing a Spanish treasure-filled galleon known as \"the prize of all the oceans,\" it had wrecked on a desolate island off the coast of Patagonia. The men, after being marooned for months and facing starvation, built the flimsy craft and sailed for more than a hundred days, traversing nearly 3,000 miles of storm-wracked seas. They were greeted as heroes.\r\n\r\nBut then . . . six months later, another, even more decrepit craft landed on the coast of Chile. This boat contained just three castaways, and they told a very different story. The thirty sailors who landed in Brazil were not heroes - they were mutineers. The first group responded with countercharges of their own, of a tyrannical and murderous senior officer and his henchmen. It became clear that while stranded on the island the crew had fallen into anarchy, with warring factions fighting for dominion over the barren wilderness. As accusations of treachery and murder flew, the Admiralty convened a court martial to determine who was telling the truth. The stakes were life-and-death--for whomever the court found guilty could hang.\r\n\r\nThe Wager is a grand tale of human behavior at the extremes told by one of our greatest nonfiction writers. Grann\'s recreation of the hidden world on a British warship rivals the work of Patrick O\'Brian, his portrayal of the castaways\' desperate straits stands up to the classics of survival writing such as The Endurance, and his account of the court martial has the savvy of a Scott Turow thriller. As always with Grann\'s work, the incredible twists of the narrative hold the reader spellbound.', 'thewager.jpg', 4501.86, 0.00),
(22, 'Masters of the Air', 'Donald L. Miller', 'Thriller', 'Masters of the Air is the deeply personal story of the American bomber boys in World War II who brought the war to Hitler\'s doorstep. With the narrative power of fiction, Donald Miller takes readers on a harrowing ride through the fire-filled skies over Berlin, Hanover, and Dresden and describes the terrible cost of bombing for the German people.\r\n\r\nFighting at 25,000 feet in thin, freezing air that no warriors had ever encountered before, bomber crews battled new kinds of assaults on body and mind. Air combat was deadly but intermittent: periods of inactivity and anxiety were followed by short bursts of fire and fear. Unlike infantrymen, bomber boys slept on clean sheets, drank beer in local pubs, and danced to the swing music of Glenn Miller\'s Air Force band, which toured U.S. air bases in England. But they had a much greater chance of dying than ground soldiers. In 1943, an American bomber crewman stood only a one-in-five chance of surviving his tour of duty, twenty-five missions. The Eighth Air Force lost more men in the war than the U.S. Marine Corps.\r\n\r\nThe bomber crews were an elite group of warriors who were a microcosm of America -- white America, anyway. (African-Americans could not serve in the Eighth Air Force except in a support capacity.) The actor Jimmy Stewart was a bomber boy, and so was the \"King of Hollywood,\" Clark Gable. And the air war was filmed by Oscar-winning director William Wyler and covered by reporters like Andy Rooney and Walter Cronkite, all of whom flew combat missions with the men. The Anglo-American bombing campaign against Nazi Germany was the longest military campaign of World War II, a war within a war. Until Allied soldiers crossed into Germany in the final months of the war, it was the only battle fought inside the German homeland.\r\n\r\nStrategic bombing did not win the war, but the war could not have been won without it. American airpower destroyed the rail facilities and oil refineries that supplied the German war machine. The bombing campaign was a shared enterprise: the British flew under the cover of night while American bombers attacked by day, a technique that British commanders thought was suicidal.\r\n\r\nMasters of the Air is a story, as well, of life in wartime England and in the German prison camps, where tens of thousands of airmen spent part of the war. It ends with a vivid description of the grisly hunger marches captured airmen were forced to make near the end of the war through the country their bombs destroyed.\r\n\r\nDrawn from recent interviews, oral histories, and American, British, German, and other archives, Masters of the Air is an authoritative, deeply moving account of the world\'s first and only bomber war.', 'mastersoftheair.jpg', 4501.86, 0.00),
(23, 'Sociopath', 'Patric Gagne', 'Biography', 'A fascinating, revelatory memoir revealing the author’s struggle to come to terms with her own sociopathy and shed light on the often maligned and misunderstood mental disorder.\r\n\r\nPatric Gagne realized she made others uncomfortable before she started kindergarten. Something about her caused people to react in a way she didn’t understand. She suspected it was because she didn’t feel things the way other kids did. Emotions like fear, guilt, and empathy eluded her. For the most part, she felt nothing. And she didn’t like the way that “nothing” felt.\r\n\r\nShe did her best to pretend she was like everyone else, but the constant pressure to conform to a society she knew rejected anyone like her was unbearable. So Patric stole. She lied. She was occasionally violent. She became an expert lock-picker and home-invader. All with the goal of replacing the nothingness with...something.\r\n\r\nIn college, Patric finally confirmed what she’d long suspected. She was a sociopath. But even though it was the very first personality disorder identified—well over 200 years ago—sociopathy had been neglected by mental health professionals for decades. She was told there was no treatment, no hope for a normal life. She found herself haunted by sociopaths in pop culture, madmen and evil villains who are considered monsters. Her future looked grim.\r\n\r\nBut when Patric reconnects with an old flame, she gets a glimpse of a future beyond her diagnosis. If she’s capable of love, it must mean that she isn’t a monster. With the help of her sweetheart (and some curious characters she meets along the way) she embarks on a mission to prove that the millions of Americans who share her diagnosis aren’t all monsters either.\r\n\r\nThis is the inspiring story of her journey to change her fate and how she managed to build a life full of love and hope.', 'sociopath.jpg', 4173.87, 3600.99),
(24, 'Knife', 'Salman Rushdie', 'Biography', 'From internationally renowned writer and Booker Prize winner Salman Rushdie, a searing, deeply personal account of enduring—and surviving—an attempt on his life thirty years after the fatwa that was ordered against him\r\n\r\nOn the morning of August 12, 2022, Salman Rushdie was standing onstage at the Chautauqua Institution, preparing to give a lecture on the importance of keeping writers safe from harm, when a man in black—black clothes, black mask—rushed down the aisle toward him, wielding a knife. His first thought: So it’s you. Here you are.\r\n\r\nWhat followed was a horrific act of violence that shook the literary world and beyond. Now, for the first time, and in unforgettable detail, Rushdie relives the traumatic events of that day and its aftermath, as well as his journey toward physical recovery and the healing that was made possible by the love and support of his wife, Eliza, his family, his army of doctors and physical therapists, and his community of readers worldwide.\r\n\r\nKnife is Rushdie at the peak of his powers, writing with urgency, with gravity, with unflinching honesty. It is also a deeply moving reminder of literature’s capacity to make sense of the unthinkable, an intimate and life-affirming meditation on life, loss, love, art—and finding the strength to stand up again.', 'knife.jpg', 4469.02, 4000.99);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int NOT NULL AUTO_INCREMENT,
  `user_name` varchar(100) NOT NULL,
  `user_email` varchar(100) NOT NULL,
  `user_password` varchar(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `UX_Constraint` (`user_email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf16;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
